[package]
name = "fltk-theme"
version = "0.1.1"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"
description = "A theming crate for fltk-rs"
repository = "https://github.com/fltk-rs/fltk-theme"
documentation = "https://docs.rs/fltk-theme"
keywords = ["gui", "ui", "widgets", "bindings", "graphics"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

[dependencies]
fltk = "1.1.3"